spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    username: root
    password: my_secret_pw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  #Because it's an example project we don't need to persist data between application executions.
    database: mysql
    show-sql: true